apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-flower
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: andresdev3/go-api-flower
          image: andresdev3/go-api-flower:latest
