apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api-flower
  template:
    metadata:
      labels:
        app: go-api-flower
    spec:
      containers:
        - name: flower-api
          image: andresdev3/go-api-flower:latest
          ports:
            - containerPort: 8080